services:
  db:
      image: postgres:16.2
      container_name: 'db'
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: symon
        POSTGRES_DB: pharmacy_users
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data